### ISSUE TITLE
Deps error

### ISSUE THREAD

**Issue by windchime-yk** [windchime-yk/dictionary#1]
deno-utilの依存関係を`import_map.json`に書かないと、以下のようなエラーが出てvelociraptorのコマンドが動作しない。
``` bash
error: Relative import path "path" not prefixed with / or ./ or ../ from "https://raw.githubusercontent.com/windchime-yk/deno-util/v1.0.0/file.ts"
error: Failed at the build script
```
なお、以下コマンドでも同様のエラーが出る
``` bash
deno run --import-map=import_map.json --unstable --allow-write --allow-read mod.ts
```

## 再現方法
1. `import_map.json`から`path`を削除
2. `vr build`か`deno run --import-map=import_map.json --unstable --allow-write --allow-read mod.ts`をコマンドラインで叩く

## Denoバージョン情報
```
deno 1.14.3 (release, x86_64-apple-darwin)
v8 9.4.146.19
typescript 4.4.2
```

## 依存関係
``` json
{
  "imports": {
    "path": "https://deno.land/std@0.108.0/path/mod.ts",
    "asserts": "https://deno.land/std@0.110.0/testing/asserts.ts",
    "util": "https://pax.deno.dev/windchime-yk/deno-util@v1.0.0/file.ts",
    "fs": "https://deno.land/std@0.78.0/fs/mod.ts"
  }
}
```

**Comment by kt3k** [comment]
deno-util が使っている import map は deno-util を使う側 (dictionary) からは見えないので、というのがこの現象の理由になるかなと思います。

package.json と違って各 module が自分の import map を持てるような仕組みにはなっていないので、deno-util のような、誰かから使われる前提のライブラリは import map を指定しないのが現状ベストプラクティスになっているように思います

**Comment by windchime-yk** [comment]
@kt3k 
なるほどぉ……。
そういうことなんですね。ありがとうございます！:pray:
deno-util修正します。
